export const PATIENT_COLLECTION = 'patients'
export const CAREGIVER_COLLECTION = 'caregivers'
export const GUARDIAN_COLLECTION = 'guardians'
export const ERROR_CAREGIVER_PROFILE_DOES_NOT_EXIST = "ERROR_CAREGIVER_PROFILE_DOES_NOT_EXIST"
export const ERROR_GUARDIAN_PROFILE_DOES_NOT_EXIST = "ERROR_GUARDIAN_PROFILE_DOES_NOT_EXIST"