export const PATIENT_COLLECTION = 'patients'
export const CAREGIVER_COLLECTION = 'caregivers'
export const GUARDIAN_COLLECTION = 'guardians'
export const PATIENT_TOKEN_COLLECTION = 'patient_tokens'
export const ERROR_CAREGIVER_PROFILE_DOES_NOT_EXIST = "ERROR_CAREGIVER_PROFILE_DOES_NOT_EXIST"
export const ERROR_GUARDIAN_PROFILE_DOES_NOT_EXIST = "ERROR_GUARDIAN_PROFILE_DOES_NOT_EXIST"
export const ERROR_INVALID_PATIENT_TOKEN = 'ERROR_INVALID_PATIENT_TOKEN'
